// Copyright 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//! Generated protobuf and gRPC types for the Triton Inference Server protocol.
//!
//! These modules are auto-generated by `tonic-build` from the Triton protobuf
//! definitions. The [`inference`] module contains the core inference service
//! types and the gRPC client stub. The [`grpc_health`] module contains the
//! standard gRPC health checking protocol types.

/// Generated types for the `inference` protobuf package.
///
/// This module contains all message types, enums, and the
/// [`grpc_inference_service_client::GrpcInferenceServiceClient`] gRPC stub
/// generated from `grpc_service.proto` and `model_config.proto`.
pub mod inference {
    tonic::include_proto!("inference");
}

/// Generated types for the `grpc.health.v1` protobuf package.
///
/// This module contains the standard gRPC health checking types from
/// `health.proto`, including the [`health_client::HealthClient`] stub.
pub mod grpc_health {
    tonic::include_proto!("grpc.health.v1");
}
